import Foundation
import Testing
@testable import CompanionKit

/// Port of pyatv's `tests/support/test_opack.py` (canonical) and
/// nodeatv's `tests/support/opack.test.ts`. Hex byte vectors are carried
/// over verbatim from those files (or, for the very large pointer vector,
/// regenerated byte-for-byte from `pyatv.support.opack` directly) to prove
/// wire compatibility.
@Suite struct OPACKPackTests {
    @Test func unsupportedAbsoluteTimeThrows() {
        // pyatv/opack.ts both raise on packing a datetime/Date ("absolute
        // time" is explicitly unimplemented on the wire).
        #expect(throws: OPACKError.self) {
            try OPACK.pack(.absoluteTime(Date()))
        }
    }

    @Test func boolean() throws {
        #expect(try OPACK.pack(.bool(true)) == hexData("01"))
        #expect(try OPACK.pack(.bool(false)) == hexData("02"))
    }

    @Test func none() throws {
        #expect(try OPACK.pack(.null) == hexData("04"))
    }

    @Test func uuid() throws {
        let u = UUID(uuidString: "12345678-1234-5678-1234-567812345678")!
        #expect(try OPACK.pack(.uuid(u)) == hexData("05") + hexData("12345678123456781234567812345678"))
    }

    @Test func smallIntegers() throws {
        #expect(try OPACK.pack(.int(0)) == hexData("08"))
        #expect(try OPACK.pack(.int(0xF)) == hexData("17"))
        #expect(try OPACK.pack(.int(0x27)) == hexData("2f"))
    }

    @Test func largerIntegers() throws {
        #expect(try OPACK.pack(.int(0x28)) == hexData("3028"))
        #expect(try OPACK.pack(.int(0x1FF)) == hexData("31ff01"))
        #expect(try OPACK.pack(.int(0x1FFFFFF)) == hexData("32ffffff01"))
        #expect(try OPACK.pack(.int(0x1FFFFFFFFFFFFFF)) == hexData("33ffffffffffffff01"))
    }

    @Test func sizedIntegers() throws {
        #expect(try OPACK.pack(.int(0x1, sizeHint: 1)) == hexData("3001"))
        #expect(try OPACK.pack(.int(0x1, sizeHint: 2)) == hexData("310100"))
        #expect(try OPACK.pack(.int(0x1, sizeHint: 4)) == hexData("3201000000"))
        #expect(try OPACK.pack(.int(0x1, sizeHint: 8)) == hexData("330100000000000000"))
    }

    @Test func float64() throws {
        #expect(try OPACK.pack(.double(1.0)) == hexData("36000000000000f03f"))
    }

    @Test func shortStrings() throws {
        #expect(try OPACK.pack(.string("a")) == hexData("4161"))
        #expect(try OPACK.pack(.string("abc")) == hexData("43616263"))
        #expect(try OPACK.pack(.string(String(repeating: "a", count: 0x20))) == hexData("60") + Data(repeating: 0x61, count: 0x20))
    }

    @Test func longerStrings() throws {
        #expect(try OPACK.pack(.string(String(repeating: "a", count: 33))) == hexData("6121") + Data(repeating: 0x61, count: 33))
        #expect(try OPACK.pack(.string(String(repeating: "a", count: 256))) == hexData("620001") + Data(repeating: 0x61, count: 256))
    }

    @Test func shortRawBytes() throws {
        #expect(try OPACK.pack(.data(hexData("ac"))) == hexData("71ac"))
        #expect(try OPACK.pack(.data(hexData("123456"))) == hexData("73123456"))
        #expect(try OPACK.pack(.data(Data(repeating: 0xad, count: 0x20))) == hexData("90") + Data(repeating: 0xad, count: 0x20))
    }

    @Test func longerRawBytes() throws {
        #expect(try OPACK.pack(.data(Data(repeating: 0x61, count: 33))) == hexData("9121") + Data(repeating: 0x61, count: 33))
        #expect(try OPACK.pack(.data(Data(repeating: 0x61, count: 256))) == hexData("920001") + Data(repeating: 0x61, count: 256))
        #expect(try OPACK.pack(.data(Data(repeating: 0x61, count: 65536))) == hexData("9300000100") + Data(repeating: 0x61, count: 65536))
    }

    @Test func array() throws {
        #expect(try OPACK.pack(.array([])) == hexData("d0"))
        #expect(try OPACK.pack([1, "test", false]) == hexData("d3094474657374 02"))
        #expect(try OPACK.pack([[true]]) == hexData("d1d101"))
    }

    @Test func endlessArray() throws {
        let arr = OPACKValue.array(Array(repeating: .string("a"), count: 15))
        let expected = hexData("df4161") + Data(repeating: 0xa0, count: 14) + hexData("03")
        #expect(try OPACK.pack(arr) == expected)
    }

    @Test func dict() throws {
        #expect(try OPACK.pack(.dictionary([])) == hexData("e0"))
        #expect(try OPACK.pack(["a": 12, false: nil]) == hexData("e2 41 61 14 02 04"))
        #expect(try OPACK.pack([true: ["a": 2]]) == hexData("e1 01 e1 41 61 0a"))
    }

    @Test func endlessDict() throws {
        var pairs: [(OPACKValue, OPACKValue)] = []
        for x in stride(from: 97, to: 127, by: 2) {
            pairs.append((.string(String(UnicodeScalar(x)!)), .string(String(UnicodeScalar(x + 1)!))))
        }
        var expected = hexData("ef")
        for x in 97..<127 {
            expected.append(0x41)
            expected.append(UInt8(x))
        }
        expected.append(0x03)
        #expect(try OPACK.pack(.dictionary(pairs)) == expected)
    }

    @Test func ptr() throws {
        #expect(try OPACK.pack(["a", "a"]) == hexData("d24161a0"))
        #expect(try OPACK.pack(["foo", "bar", "foo", "bar"]) == hexData("d443666f6f43626172a0a1"))
        #expect(try OPACK.pack(["a": "b", "c": ["d": "a"], "d": true]) == hexData("e3416141624163e14164a0a301"))
    }

    @Test func morePtr() throws {
        let data = OPACKVectors.moreData
        #expect(try OPACK.pack(.array(data + data)) == hexData(OPACKVectors.morePtrHex))
    }
}

@Suite struct OPACKUnpackTests {
    @Test func unsupportedTypeThrows() {
        #expect(throws: OPACKError.self) {
            try OPACK.unpack(hexData("00"))
        }
    }

    @Test func boolean() throws {
        #expect(try OPACK.unpack(hexData("01")) == .bool(true))
        #expect(try OPACK.unpack(hexData("02")) == .bool(false))
    }

    @Test func none() throws {
        #expect(try OPACK.unpack(hexData("04")) == .null)
    }

    @Test func uuid() throws {
        let expected = UUID(uuidString: "12345678-1234-5678-1234-567812345678")!
        #expect(try OPACK.unpack(hexData("05") + hexData("12345678123456781234567812345678")) == .uuid(expected))
    }

    @Test func absoluteTimeDecodesAsInteger() throws {
        // Dummy implementation in both references: 0x06 is parsed as a
        // plain little-endian integer, it does NOT throw on decode (only
        // packing a Date/datetime is unimplemented).
        #expect(try OPACK.unpack(hexData("060100000000000000")) == .int(1))
    }

    @Test func smallIntegers() throws {
        #expect(try OPACK.unpack(hexData("08")) == .int(0))
        #expect(try OPACK.unpack(hexData("17")) == .int(0xF))
        #expect(try OPACK.unpack(hexData("2f")) == .int(0x27))
    }

    @Test func largerIntegers() throws {
        #expect(try OPACK.unpack(hexData("3028")) == .int(0x28))
        #expect(try OPACK.unpack(hexData("31ff01")) == .int(0x1FF))
        #expect(try OPACK.unpack(hexData("32ffffff01")) == .int(0x1FFFFFF))
        #expect(try OPACK.unpack(hexData("33ffffffffffffff01")) == .int(0x1FFFFFFFFFFFFFF))
    }

    @Test func sizedIntegersPreserveSizeHint() throws {
        guard case .int(_, let s1) = try OPACK.unpack(hexData("3001")) else { Issue.record("expected .int"); return }
        guard case .int(_, let s2) = try OPACK.unpack(hexData("310100")) else { Issue.record("expected .int"); return }
        guard case .int(_, let s4) = try OPACK.unpack(hexData("3201000000")) else { Issue.record("expected .int"); return }
        guard case .int(_, let s8) = try OPACK.unpack(hexData("330100000000000000")) else { Issue.record("expected .int"); return }
        #expect(s1 == 1)
        #expect(s2 == 2)
        #expect(s4 == 4)
        #expect(s8 == 8)
    }

    @Test func float32() throws {
        #expect(try OPACK.unpack(hexData("350000803f")) == .double(1.0))
    }

    @Test func float64() throws {
        #expect(try OPACK.unpack(hexData("36000000000000f03f")) == .double(1.0))
    }

    @Test func shortStrings() throws {
        #expect(try OPACK.unpack(hexData("4161")) == .string("a"))
        #expect(try OPACK.unpack(hexData("43616263")) == .string("abc"))
        #expect(try OPACK.unpack(hexData("60") + Data(repeating: 0x61, count: 0x20)) == .string(String(repeating: "a", count: 0x20)))
    }

    @Test func longerStrings() throws {
        #expect(try OPACK.unpack(hexData("6121") + Data(repeating: 0x61, count: 33)) == .string(String(repeating: "a", count: 33)))
        #expect(try OPACK.unpack(hexData("620001") + Data(repeating: 0x61, count: 256)) == .string(String(repeating: "a", count: 256)))
    }

    @Test func shortRawBytes() throws {
        #expect(try OPACK.unpack(hexData("71ac")) == .data(hexData("ac")))
        #expect(try OPACK.unpack(hexData("73123456")) == .data(hexData("123456")))
        #expect(try OPACK.unpack(hexData("90") + Data(repeating: 0xad, count: 0x20)) == .data(Data(repeating: 0xad, count: 0x20)))
    }

    @Test func longerRawBytes() throws {
        #expect(try OPACK.unpack(hexData("9121") + Data(repeating: 0x61, count: 33)) == .data(Data(repeating: 0x61, count: 33)))
        #expect(try OPACK.unpack(hexData("920001") + Data(repeating: 0x61, count: 256)) == .data(Data(repeating: 0x61, count: 256)))
        #expect(try OPACK.unpack(hexData("93000001 00") + Data(repeating: 0x61, count: 65536)) == .data(Data(repeating: 0x61, count: 65536)))
    }

    @Test func array() throws {
        #expect(try OPACK.unpack(hexData("d0")) == .array([]))
        #expect(try OPACK.unpack(hexData("d3094474657374 02")) == [1, "test", false])
        #expect(try OPACK.unpack(hexData("d1d101")) == [[true]])
    }

    @Test func endlessArray() throws {
        let list1 = hexData("df4161") + Data(repeating: 0xa0, count: 15) + hexData("03")
        let list2 = hexData("df4162") + Data(repeating: 0xa1, count: 15) + hexData("03")
        #expect(try OPACK.unpack(list1) == .array(Array(repeating: .string("a"), count: 16)))
        #expect(try OPACK.unpack(hexData("d2") + list1 + list2) == .array([
            .array(Array(repeating: .string("a"), count: 16)),
            .array(Array(repeating: .string("b"), count: 16)),
        ]))
    }

    @Test func dict() throws {
        #expect(try OPACK.unpack(hexData("e0")) == .dictionary([]))
        #expect(try OPACK.unpack(hexData("e2 41 61 14 02 04")) == ["a": 12, false: nil])
        #expect(try OPACK.unpack(hexData("e1 01 e1 41 61 0a")) == [true: ["a": 2]])
    }

    @Test func endlessDict() throws {
        var manualExpected: [(OPACKValue, OPACKValue)] = []
        for x in stride(from: 97, to: 127, by: 2) {
            manualExpected.append((.string(String(UnicodeScalar(x)!)), .string(String(UnicodeScalar(x + 1)!))))
        }
        var wire = hexData("ef")
        for x in 97..<127 {
            wire.append(0x41)
            wire.append(UInt8(x))
        }
        wire.append(0x03)
        #expect(try OPACK.unpack(wire) == .dictionary(manualExpected))
    }

    @Test func ptr() throws {
        #expect(try OPACK.unpack(hexData("d24161a0")) == ["a", "a"])
        #expect(try OPACK.unpack(hexData("d443666f6f43626172a0a1")) == ["foo", "bar", "foo", "bar"])
        #expect(try OPACK.unpack(hexData("e3416141624163e14164a0a301")) == ["a": "b", "c": ["d": "a"], "d": true])
    }

    @Test func morePtr() throws {
        let expected = OPACKVectors.moreData
        #expect(try OPACK.unpack(hexData(OPACKVectors.morePtrHex)) == .array(expected + expected))
    }

    @Test func uid() throws {
        #expect(try OPACK.unpack(hexData("df300130 02c10103")) == [1, 2, 2])
        #expect(try OPACK.unpack(hexData("df300130 02c2010003")) == [1, 2, 2])
        #expect(try OPACK.unpack(hexData("df300130 02c301000003")) == [1, 2, 2])
        #expect(try OPACK.unpack(hexData("df300130 02c40100000003")) == [1, 2, 2])
    }

    @Test func trailingDataIsIgnored() throws {
        // OPACK.unpack decodes only the first value and ignores anything
        // after it, matching pyatv's `unpack` returning `(value, remaining)`
        // and leaving `remaining` for the caller to discard.
        let packed = try OPACK.pack(.bool(true)) + hexData("ffff")
        #expect(try OPACK.unpack(packed) == .bool(true))
    }

    @Test func hugeLengthPrefixThrowsNotTraps() throws {
        // A tag-0x94 byte-string with an 8-byte length whose top bit is set
        // (>= 2^63) must surface as a thrown error, not trap the Int(_:)
        // conversion — these frames are unauthenticated during pairing.
        let hostile = hexData("94 ffffffffffffffff")
        #expect(throws: OPACKError.self) {
            _ = try OPACK.unpack(hostile)
        }
        // And an 8-byte integer above Int.max stays a UInt64, decoding without
        // trapping. asInt then rejects it (nil) rather than trapping Int(_:),
        // while asUInt64 preserves it.
        let big = try OPACK.unpack(hexData("33 ffffffffffffffff"))
        #expect(big == .int(.max, sizeHint: 8))
        #expect(big.asInt == nil)
        #expect(big.asUInt64 == UInt64.max)
    }

    @Test func golden() throws {
        // Port of test_opack.py::test_golden / opack.test.ts's roundtrip
        // test: pack a realistic nested Companion "_systemInfo" payload and
        // confirm it round-trips through unpack unchanged.
        let hkUID = UUID(uuidString: "17ed160a-81f8-4488-962c-6b1a83eb0081")!
        let original: OPACKValue = [
            "_i": "_systemInfo",
            "_x": 1_254_122_577,
            "_btHP": false,
            "_c": [
                "_pubID": "AA:BB:CC:DD:EE:FF",
                "_sv": "230.1",
                "_bf": 0,
                "_siriInfo": [
                    "collectorElectionVersion": 1.0,
                    "deviceCapabilities": ["seymourEnabled": 1, "voiceTriggerEnabled": 2],
                    "sharedDataProtoBuf": OPACKValue.data(Data(repeating: 0x08, count: 512)),
                ],
                "_stA": [
                    "com.apple.LiveAudio",
                    "com.apple.siri.wakeup",
                    "com.apple.Seymour",
                    "com.apple.announce",
                    "com.apple.coreduet.sync",
                    "com.apple.SeymourSession",
                ],
                "_clFl": 128,
                "_idsID": "44E14ABC-DDDD-4188-B661-11BAAAF6ECDE",
                "_hkUID": OPACKValue.array([.uuid(hkUID)]),
                "_dC": "1",
                "_sf": 256,
                "model": "iPhone10,6",
                "name": "iPhone",
                "_i": "6c62fca18b11",
            ],
            "_t": 2,
        ]

        let packed = try OPACK.pack(original)
        let unpacked = try OPACK.unpack(packed)
        #expect(unpacked == original)
    }
}

/// Shared huge pointer-referencing vector (`test_pack_more_ptr` /
/// `test_unpack_more_ptr` in test_opack.py): 257 unique single/double-byte
/// raw-bytes values (UTF-8 encodings of code points 0...256) followed by the
/// same 257 values again, all inside one 514-element endless array, forcing
/// both 1-byte (0xA0-0xC0) and multi-byte (0xC1) backreference pointer
/// forms. The hex below was regenerated byte-for-byte from
/// `pyatv.support.opack.pack` to avoid manual transcription of ~1100 bytes.
enum OPACKVectors {
    static let moreData: [OPACKValue] = (0...256).map { codePoint in
        .data(Data(String(UnicodeScalar(codePoint)!).utf8))
    }

    static let morePtrHex =
        "df7100710171027103710471057106710771087109710a710b710c710d710e710f"
        + "7110711171127113711471157116711771187119711a711b711c711d711e711f"
        + "7120712171227123712471257126712771287129712a712b712c712d712e712f"
        + "7130713171327133713471357136713771387139713a713b713c713d713e713f"
        + "7140714171427143714471457146714771487149714a714b714c714d714e714f"
        + "7150715171527153715471557156715771587159715a715b715c715d715e715f"
        + "7160716171627163716471657166716771687169716a716b716c716d716e716f"
        + "7170717171727173717471757176717771787179717a717b717c717d717e717f"
        + "72c28072c28172c28272c28372c28472c28572c28672c28772c28872c28972c28a"
        + "72c28b72c28c72c28d72c28e72c28f72c29072c29172c29272c29372c29472c295"
        + "72c29672c29772c29872c29972c29a72c29b72c29c72c29d72c29e72c29f72c2a0"
        + "72c2a172c2a272c2a372c2a472c2a572c2a672c2a772c2a872c2a972c2aa72c2ab"
        + "72c2ac72c2ad72c2ae72c2af72c2b072c2b172c2b272c2b372c2b472c2b572c2b6"
        + "72c2b772c2b872c2b972c2ba72c2bb72c2bc72c2bd72c2be72c2bf72c38072c381"
        + "72c38272c38372c38472c38572c38672c38772c38872c38972c38a72c38b72c38c"
        + "72c38d72c38e72c38f72c39072c39172c39272c39372c39472c39572c39672c397"
        + "72c39872c39972c39a72c39b72c39c72c39d72c39e72c39f72c3a072c3a172c3a2"
        + "72c3a372c3a472c3a572c3a672c3a772c3a872c3a972c3aa72c3ab72c3ac72c3ad"
        + "72c3ae72c3af72c3b072c3b172c3b272c3b372c3b472c3b572c3b672c3b772c3b8"
        + "72c3b972c3ba72c3bb72c3bc72c3bd72c3be72c3bf72c480a0a1a2a3a4a5a6a7a8"
        + "a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c121c122c123c124c1"
        + "25c126c127c128c129c12ac12bc12cc12dc12ec12fc130c131c132c133c134c135"
        + "c136c137c138c139c13ac13bc13cc13dc13ec13fc140c141c142c143c144c145c1"
        + "46c147c148c149c14ac14bc14cc14dc14ec14fc150c151c152c153c154c155c156"
        + "c157c158c159c15ac15bc15cc15dc15ec15fc160c161c162c163c164c165c166c1"
        + "67c168c169c16ac16bc16cc16dc16ec16fc170c171c172c173c174c175c176c177"
        + "c178c179c17ac17bc17cc17dc17ec17fc180c181c182c183c184c185c186c187c1"
        + "88c189c18ac18bc18cc18dc18ec18fc190c191c192c193c194c195c196c197c198"
        + "c199c19ac19bc19cc19dc19ec19fc1a0c1a1c1a2c1a3c1a4c1a5c1a6c1a7c1a8c1"
        + "a9c1aac1abc1acc1adc1aec1afc1b0c1b1c1b2c1b3c1b4c1b5c1b6c1b7c1b8c1b9"
        + "c1bac1bbc1bcc1bdc1bec1bfc1c0c1c1c1c2c1c3c1c4c1c5c1c6c1c7c1c8c1c9c1"
        + "cac1cbc1ccc1cdc1cec1cfc1d0c1d1c1d2c1d3c1d4c1d5c1d6c1d7c1d8c1d9c1da"
        + "c1dbc1dcc1ddc1dec1dfc1e0c1e1c1e2c1e3c1e4c1e5c1e6c1e7c1e8c1e9c1eac1"
        + "ebc1ecc1edc1eec1efc1f0c1f1c1f2c1f3c1f4c1f5c1f6c1f7c1f8c1f9c1fac1fb"
        + "c1fcc1fdc1fec1ffc2000103"
}
